// This file is autogenerated. Do not modify.

struct LocalizeStrings {


	struct Home {


		struct Nav {

			static var titleString: String { get { return "HOME.NAV.TITLE".localized() } }
			static func title() -> LocalizeKey { return LocalizeKey(keyPath: "HOME.NAV.TITLE") }

		}

	}

}

